name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Backend: Setup and Test
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
        
      # Debug: Verify Go installation
      - name: Check Go Version
        run: go version
      
      - name: Install Dependencies
        working-directory: backend
        run: go mod tidy

      - name: Run Backend Tests
        working-directory: backend
        run: go test ./... -v

      - name: Lint Backend
        working-directory: backend
        run: go vet ./...

      # Frontend: Setup and Test
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Lint Frontend
        working-directory: frontend
        run: npm run lint

      - name: Test Frontend
        working-directory: frontend
        run: npm test -- --watchAll=false

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        working-directory: backend
        run: docker build -t task-manager-backend .

      - name: Build Frontend Docker Image
        working-directory: frontend
        run: docker build -t task-manager-frontend .
