name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Dependencies
        working-directory: backend
        run: go mod tidy

      - name: Run Backend Tests
        working-directory: backend
        run: go test ./... -v

      - name: Lint Backend
        working-directory: backend
        run: go vet ./...

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Lint Frontend
        working-directory: frontend
        run: npm run lint

      - name: Test Frontend
        working-directory: frontend
        run: npm test -- --watchAll=false

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag shay23bra/task-manager-backend:latest \
            --push \
            ./backend

      - name: Build and Push Frontend Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag shay23bra/task-manager-frontend:latest \
            --push \
            ./frontend